from django.urls import path
from .views import (
    add_student_to_module_run,
    delete_user,
    reset_user_password,
    home,
    login_view,
    logout_view,
    faculty_home,
    faculty_students_panel,
    faculty_view_class_panel,
    faculty_assignment_detail_view,
    faculty_assignment_detail_ajax,
    student_home,
    student_module_assignments_panel,
    student_submit_assignment,
    student_delete_submission,
    student_module_materials_panel,
    module_attendance_panel,
    course_materials_panel,
    add_course_material,
    delete_course_material,
    module_assignments_panel,
    add_module_assignment,
    delete_module_assignment,
    delete_assignment_file,
    update_module_assignment,
    assignment_submission_form,
    submit_assignment,
    grade_assignment_form,
    grade_assignment_submission,
    delete_assignment_submission,
    module_students_panel,
    remove_student_from_module_run,
    save_module_attendance,
    module_run_readings,
)

urlpatterns = [
    path("", login_view, name="login"),
    path("home/", home, name="home"),
    path("faculty/", faculty_home, name="faculty_home"),
    path("faculty/students/panel/", faculty_students_panel, name="faculty_students_panel"),
    path("faculty/module-runs/<uuid:module_run_id>/view-class/", faculty_view_class_panel, name="faculty_view_class_panel"),
    path("faculty/assignments/<uuid:assignment_id>/", faculty_assignment_detail_view, name="faculty_assignment_detail_view"),
    path("faculty/assignments/<uuid:assignment_id>/detail/", faculty_assignment_detail_ajax, name="faculty_assignment_detail_ajax"),
    path("student/", student_home, name="student_home"),
    path("logout/", logout_view, name="logout"),
    path("users/delete/<uuid:user_id>/", delete_user, name="delete_user"),
    path("users/<uuid:user_id>/reset-password/", reset_user_password, name="reset_user_password"),
    path("module-runs/<uuid:module_run_id>/students/", module_students_panel, name="module_students_panel"),
    path("module-runs/<uuid:module_run_id>/students/add/", add_student_to_module_run, name="add_student_to_module_run"),
    path(
        "module-runs/<uuid:module_run_id>/students/<uuid:enrollment_id>/remove/",
        remove_student_from_module_run,
        name="remove_student_from_module_run",
    ),
    path("module-runs/<uuid:module_run_id>/attendance/", module_attendance_panel, name="module_attendance_panel"),
    path("module-runs/<uuid:module_run_id>/attendance/save/", save_module_attendance, name="save_module_attendance"),
    path("course-materials/", course_materials_panel, name="course_materials_panel"),
    path("course-materials/add/", add_course_material, name="add_course_material"),
    path("course-materials/<uuid:material_id>/delete/", delete_course_material, name="delete_course_material"),
    path("module-runs/<uuid:module_run_id>/assignments/", module_assignments_panel, name="module_assignments_panel"),
    path("module-runs/<uuid:module_run_id>/assignments/detail/", module_assignments_panel, name="module_assignments_detail"),
    path("module-runs/<uuid:module_run_id>/assignments/add/", add_module_assignment, name="add_module_assignment"),
    path(
        "module-runs/<uuid:module_run_id>/assignments/<uuid:assignment_id>/update/",
        update_module_assignment,
        name="update_module_assignment",
    ),
    path(
        "module-runs/<uuid:module_run_id>/assignments/<uuid:assignment_id>/delete/",
        delete_module_assignment,
        name="delete_module_assignment",
    ),
    path(
        "module-runs/<uuid:module_run_id>/assignments/files/<uuid:file_id>/delete/",
        delete_assignment_file,
        name="delete_assignment_file",
    ),
    path(
        "assignments/<uuid:assignment_id>/students/<uuid:student_module_id>/submit/",
        assignment_submission_form,
        name="assignment_submission_form",
    ),
    path(
        "assignments/<uuid:assignment_id>/students/<uuid:student_module_id>/submit/save/",
        submit_assignment,
        name="submit_assignment",
    ),
    path(
        "assignments/<uuid:assignment_id>/students/<uuid:student_module_id>/grade/",
        grade_assignment_form,
        name="grade_assignment_form",
    ),
    path(
        "assignments/<uuid:assignment_id>/students/<uuid:student_module_id>/grade/save/",
        grade_assignment_submission,
        name="grade_assignment_submission",
    ),
    path(
        "assignments/<uuid:assignment_id>/students/<uuid:student_module_id>/delete-submission/",
        delete_assignment_submission,
        name="delete_assignment_submission",
    ),
    path(
        "student/module-runs/<uuid:module_run_id>/assignments/",
        student_module_assignments_panel,
        name="student_module_assignments_panel",
    ),
    path(
        "student/module-runs/<uuid:module_run_id>/assignments/<uuid:assignment_id>/submit/",
        student_submit_assignment,
        name="student_submit_assignment",
    ),
    path(
        "student/submit-assignment/<uuid:assignment_id>/",
        student_submit_assignment,
        name="student_submit_assignment_simple",
    ),
    path(
        "student/module-runs/<uuid:module_run_id>/assignments/<uuid:assignment_id>/delete/",
        student_delete_submission,
        name="student_delete_submission",
    ),
    path(
        "student/modules/<uuid:module_id>/materials/",
        student_module_materials_panel,
        name="student_module_materials_panel",
    ),
    path(
        "module-runs/<uuid:module_run_id>/readings/",
        module_run_readings,
        name="module_run_readings",
    ),
]
