services:

  db:
    image: postgres:15
    container_name: lms_v2_db
    restart: always
    environment:
      POSTGRES_DB: lms
      POSTGRES_USER: lms_user
      POSTGRES_PASSWORD: lms_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  web:
    build: .
    container_name: lms_v2_web
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    depends_on:
      - db

volumes:
  postgres_data:
