# Generated by Django 5.0 on 2026-06-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0006_assignmentsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentfile',
            name='file_url',
            field=models.FileField(upload_to='assignment_files/'),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='file_url',
            field=models.FileField(upload_to='assignment_submissions/'),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='file_url',
            field=models.FileField(upload_to='course_materials/'),
        ),
    ]
