# Generated by Django 5.0 on 2026-06-06 15:45

import modules.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0007_alter_assignmentfile_file_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentfile',
            name='file_url',
            field=models.FileField(upload_to=modules.models.assignment_file_upload_path),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='file_url',
            field=models.FileField(upload_to=modules.models.assignment_submission_upload_path),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='file_url',
            field=models.FileField(upload_to=modules.models.course_material_upload_path),
        ),
    ]
