# Generated by Django 5.0 on 2026-06-10 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0008_alter_assignmentfile_file_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='resource_type',
            field=models.CharField(choices=[('REQUIRED', 'Required'), ('RECOMMENDED', 'Recommended'), ('RESOURCES', 'Resources')], default='REQUIRED', max_length=20),
        ),
    ]
