# Generated by Django 5.0 on 2026-06-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0009_coursematerial_resource_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='moduleId',
            field=models.CharField(default='MODULE-ID-PENDING', max_length=100),
        ),
    ]
