# Generated by Django 5.0 on 2026-06-12 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0010_module_moduleid'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
