# Generated by Django 5.0 on 2026-06-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0011_assignmentsubmission_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('graded', 'Graded')], default='draft', max_length=20),
        ),
    ]
