# Generated by Django 5.0 on 2026-06-16 10:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0013_assignment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_name', models.CharField(max_length=255)),
                ('vimeo_id', models.CharField(max_length=100)),
                ('order_number', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='modules.module')),
            ],
            options={
                'db_table': 'module_videos',
                'ordering': ['order_number', 'created_at'],
            },
        ),
    ]
