# Generated by Django 5.0 on 2026-06-17 07:49

from django.db import migrations, models


def populate_serial_numbers(apps, schema_editor):
    """Populate serial numbers for existing assignments"""
    Assignment = apps.get_model('modules', 'Assignment')
    
    # Get all module_runs that have assignments
    module_runs = Assignment.objects.values_list('module_run_id', flat=True).distinct()
    
    for module_run_id in module_runs:
        # Get all assignments for this module_run ordered by creation
        assignments = Assignment.objects.filter(
            module_run_id=module_run_id
        ).order_by('due_date', 'id')
        
        # Assign serial numbers starting from 1
        for index, assignment in enumerate(assignments, start=1):
            assignment.serial_number = index
            assignment.save(update_fields=['serial_number'])


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0014_modulevideo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['serial_number', '-due_date']},
        ),
        migrations.AddField(
            model_name='assignment',
            name='serial_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RunPython(populate_serial_numbers, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('module_run', 'serial_number')},
        ),
    ]
