# Generated by Django 5.0 on 2026-06-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0015_add_serial_number_to_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='serial_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
