# Generated by Django 5.0 on 2026-08-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0016_change_serial_number_to_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulerun',
            name='attendance_max_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modulerun',
            name='participation_max_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentmodule',
            name='attendance_mark',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentmodule',
            name='participation_mark',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='resource_type',
            field=models.CharField(choices=[('REQUIRED', 'Required'), ('RECOMMENDED', 'Recommended'), ('RESOURCES', 'Resources'), ('SYLLABUS', 'Syllabus')], default='REQUIRED', max_length=20),
        ),
    ]
