# Generated by Django 5.0 on 2026-09-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0017_add_attendance_participation_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulerun',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], max_length=20),
        ),
    ]
