# Generated by Django 5.0 on 2026-05-29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="serial_number",
            field=models.CharField(blank=True, db_index=True, max_length=7, null=True, unique=True),
        ),
    ]

