# Generated by Django 5.0 on 2026-04-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_academicyear_enrollment_academic_year_quarter'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='max_quarters',
            field=models.IntegerField(default=5),
        ),
    ]
