# Generated by Django 5.0 on 2026-06-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_enrollment_start_quarter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='start_quarter',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='quarters',
            field=models.ManyToManyField(blank=True, help_text='Quarters the student is enrolled in', related_name='enrollments', to='academics.quarter'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='track',
            field=models.CharField(choices=[('DIPLOMA', 'Diploma Program'), ('CERTIFICATE', 'Certificate Program')], max_length=20),
        ),
    ]
